version: '3.4'

services:
  rails:
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
      - "587:587"
    volumes:
      - ./app:/app/
      - db_data:/postgresql
      - bundle:/bundle
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
volumes:
  bundle:
  db_data:
